# Generated by Django 4.1.1 on 2022-11-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='summary',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
